export const ENV_VARS = [
  "VITE_APIKEY",
  "VITE_AUTHDOMAIN",
  "VITE_PROJECTID",
  "VITE_STORAGEBUCKET",
  "VITE_MESSAGINGSENDERID",
  "VITE_APPID",
  "VITE_MEASUREMENTID",
  "VITE_RAWGAPIKEY",
  "VITE_RAWGBASEURL",
];
